# This is a sample funding file.
# For more see https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors
# or https://github.com/blog/2333-experimental-funding-options-on-github

# List your funding options here
# For example:
# github: [username]
# patreon: [username]

# You can also use a single funding platform:
# open_collective: [org-name]
# ko_fi: [username]
# liberapay: [username]
# tidelift: [package-name]
# community_bridge: [project-name]
# custom: [url]
